apiVersion: v1
kind: Service
metadata:
  name: {{ include "vsai-view-app.fullname" . }}
  labels:
    {{- include "vsai-view-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
      nodePort: 30080
  selector:
    {{- include "vsai-view-app.selectorLabels" . | nindent 4 }}
