path_config:
  harbor_base: ./harbor_values
  viewapps: ./helm_chart/vsai-view-app
  basicapps: ./helm_chart/vsai-bridge-app
  image_path: ./images 

project_list: ["basic-apps", "openjdk", "common_template", "visionai_template"]

